### ISSUE TITLE
Unresolved reference: foundation

### ISSUE THREAD

**Issue by ismai117** [andremion/RetroBeat#6]
HI, I came across your article due to having the same problem. I tried importing the NSKeyValueObservingProtocol, but the package name isn't recognised

**Comment by andremion** [comment]
Hi,

Have you defined the package name in the build file or in the def file?

Look at this example: [nskeyvalueobserving.def](https://github.com/andremion/RetroBeat/blob/main/shared/src/nativeInterop/cinterop/nskeyvalueobserving.def)

**Comment by ismai117** [comment]
it's working now, the problem was that I didn't add kotlin.mpp.enableCInteropCommonization=true in gradle.properties. 

thanks!
